spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db
    username: root
    password: 892400jj
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 80


